# Generated by Django 3.0.7 on 2020-06-18 12:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('grocer', '0002_auto_20200618_1810'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='products',
            name='view',
        ),
    ]
