# Generated by Django 3.0.7 on 2020-06-19 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grocer', '0005_remove_latestproducts_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='latestproducts',
            name='status',
            field=models.BooleanField(default=0, verbose_name=True),
            preserve_default=False,
        ),
    ]
