# Generated by Django 3.0.7 on 2020-06-19 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grocer', '0006_latestproducts_status'),
    ]

    operations = [
        migrations.DeleteModel(
            name='latestproducts',
        ),
        migrations.AddField(
            model_name='products',
            name='limg',
            field=models.ImageField(default=0, upload_to='pic'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='products',
            name='lname',
            field=models.CharField(default=0, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='products',
            name='lprice',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='products',
            name='lqty',
            field=models.CharField(default=0, max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='products',
            name='lstatus',
            field=models.BooleanField(default=0, verbose_name=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='products',
            name='status',
            field=models.BooleanField(verbose_name=True),
        ),
    ]
