# Generated by Django 3.0.7 on 2020-06-19 12:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('grocer', '0007_auto_20200619_1757'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='products',
            name='limg',
        ),
        migrations.RemoveField(
            model_name='products',
            name='lname',
        ),
        migrations.RemoveField(
            model_name='products',
            name='lprice',
        ),
        migrations.RemoveField(
            model_name='products',
            name='lqty',
        ),
        migrations.RemoveField(
            model_name='products',
            name='lstatus',
        ),
    ]
