# Generated by Django 3.0.7 on 2020-06-27 07:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('grocer', '0009_post'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='status',
        ),
    ]
