# Generated by Django 3.0.7 on 2020-07-18 08:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('grocer', '0012_products_type'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='products',
            new_name='product',
        ),
    ]
