# Generated by Django 3.0.7 on 2020-07-21 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grocer', '0015_order_totalprice'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='totalPrice',
            field=models.IntegerField(),
        ),
    ]
