# Generated by Django 3.0.7 on 2020-07-21 17:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('grocer', '0016_auto_20200721_2300'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='totalPrice',
        ),
    ]
