# Generated by Django 3.0.7 on 2020-07-21 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grocer', '0017_remove_order_totalprice'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='contact',
            field=models.IntegerField(),
        ),
    ]
